4621.dev
4reeman/current-proj pull request #29
Opened 2022-04-20 12:47 UTC by 4reeman

https://redmine.devbranch.work/issues/4621

2022-04-20 12:53 UTC, 4reeman commented
#28

2022-04-20 13:22 UTC, devbranch-vitaliy requested changes

2022-04-20 13:22 UTC, devbranch-vitaliy commented on web/modules/custom/pulses_weather/src/PulsesCityProvider.php
> +    if (!$exist) {
We need to get cities only when data doesn't exist.
```suggestion
    if (!$exist) {
      $default_city = $this->configFactory->get(WeatherSettingsForm::SETTINGS)->get('city');
      $city = $this->getCityName() ?: $default_city;
      $language = $this->user->getPreferredLangcode();
    if (!$exist) {
```

2022-04-20 15:05 UTC, 4reeman commented
@todo create one more column in custom database table for user_ip. It must be implemented because of unauthorized users have the same user_id. Since city for first unauthorized user (user_id = 0) will save in database it won`t change for another unauthorized users because of checking for the existence of an entry in the database of the city of this user is based on user_id.

2022-04-21 06:57 UTC, devbranch-vitaliy requested changes

2022-04-21 06:57 UTC, devbranch-vitaliy commented on web/modules/custom/pulses_weather/src/PulsesWeatherProvider.php
> +    }
Think about cache ID a little bit more ad say me why your implementation is wrong :)

2022-04-21 08:15 UTC, devbranch-vitaliy approved these changes

2022-04-21 08:15 UTC, merged